/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import dao.UsuarioDAO;
import javax.swing.JOptionPane;
import modelo.Usuario;
import util.Validacion;

/**
 *
 * @author LEAC2
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        setupDiseño();
        // Nota: esto es un regex progresivo (sin ^ $ porque matches() exige match completo)
        Validacion.permitirSolo(txtCorreo, "[A-Za-z0-9@._+\\-]*", 50);
        Validacion.permitirSolo(txtContra, "^[A-Za-z0-9@#$%^&+=!]{0,20}$", 20);;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresar = new javax.swing.JButton();
        lbU = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lbU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbU.setText("Correo");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Contraseña");
        jLabel2.setToolTipText("");

        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbU, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(lbU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        handleLogin(txtCorreo.getText(),txtContra.getText());
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    private UsuarioDAO usuarioDAO = new UsuarioDAO();

    // Este método se llamaría al hacer clic en el botón "Iniciar Sesión"
    public void handleLogin(String correo, String contrasena) {
        if (correo == null || correo.trim().isEmpty() || contrasena == null || contrasena.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.");
            return;
        }

        Usuario usuarioAutenticado = usuarioDAO.login(correo.trim(), contrasena);

        if (usuarioAutenticado != null) {
            abrirVentanaPrincipal(usuarioAutenticado);
        } else {
            // ❌ Credenciales inválidas
            JOptionPane.showMessageDialog(this, "Credenciales erroneas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void abrirVentanaPrincipal(Usuario usuario) {
        String rol = usuario.getRol().getNombreRol();
        // Redirigir según el rol
        switch (rol.toLowerCase()) {
            case "administrador":
                Home home = new Home(usuario);
                home.setVisible(true);
                dispose();
                // abrirVentanaAdmin();
                break;
            case "profesor":
                // abrirVentanaProfesor();
                break;
            case "alumno":
                // abrirVentanaAlumno();
                break;
            default:
                JOptionPane.showMessageDialog(this, "Rol no reconocido.", "Advertencia", JOptionPane.WARNING_MESSAGE);

                return;
        }
        // Cerrar la ventana de login
        System.out.println("Bienvenido, " + usuario.getNombre() + " (" + rol + ")");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }
    private void setupDiseño() {
        javax.swing.JPanel panel = (javax.swing.JPanel) this.getContentPane();
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel.setBackground(new java.awt.Color(0, 140, 153)); // Azul Turquesa
        java.awt.Font tituloFont = new java.awt.Font("Segoe UI", 1, 26);
        java.awt.Font labelFont = new java.awt.Font("Segoe UI", 0, 14);
        java.awt.Font inputFont = new java.awt.Font("Segoe UI", 0, 14);
        java.awt.Color blanco = java.awt.Color.WHITE;

        javax.swing.JLabel lbTitulo = new javax.swing.JLabel("Bienvenido");
        lbTitulo.setFont(tituloFont);
        lbTitulo.setForeground(blanco);
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 450, 40));

        lbU.setText("Correo Electrónico");
        lbU.setFont(labelFont);
        lbU.setForeground(blanco);
        lbU.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panel.add(lbU, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 110, 300, -1));

        txtCorreo.setFont(inputFont);
        txtCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)); // Padding interno
        panel.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 135, 300, 40));

        jLabel2.setText("Contraseña");
        jLabel2.setFont(labelFont);
        jLabel2.setForeground(blanco);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 200, 300, -1));

        txtContra.setFont(inputFont);
        txtContra.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        panel.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 225, 300, 40));

        btnIngresar.setText("INICIAR SESIÓN");
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 14));
        btnIngresar.setBackground(new java.awt.Color(255, 255, 255)); // Blanco
        btnIngresar.setForeground(new java.awt.Color(0, 140, 153));   // Letras turquesas
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        panel.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 310, 200, 45));

        this.setSize(465, 450); 

        panel.revalidate();
        panel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbU;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
