/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import util.RedImg;

/**
 *
 * @author LEAC2
 */
public class FormEjemplar extends javax.swing.JPanel {

    RedImg re = new RedImg();
    
    public FormEjemplar() {
        
    }
        public FormEjemplar(String tipo) {
        initComponents();
        //if()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtUD = new javax.swing.JTextField();
        lb = new javax.swing.JLabel();
        lbC1 = new javax.swing.JLabel();
        txtNP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        lbC2 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        txtEstado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        cbTD = new javax.swing.JComboBox<>();
        lbC3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JLabel();
        lbE = new javax.swing.JLabel();
        lbC4 = new javax.swing.JLabel();
        txtEditorial1 = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 52, 46));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Ejemplar");
        add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 16, 224, 60));

        jLabel9.setText("Título");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 149, -1));
        add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 164, -1));
        add(txtUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 270, -1));

        lb.setText("Ubicación");
        add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 149, -1));

        lbC1.setText("Campo 1");
        add(lbC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 149, -1));
        add(txtNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 164, -1));

        jLabel3.setText("Tipo de documento");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 149, 30));
        add(txtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 164, -1));
        add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 164, -1));

        lbC2.setText("Campo 2");
        add(lbC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 149, -1));

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtId.setText("Id");
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 117, -1));

        txtEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEstado.setText("Estado");
        add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 117, -1));

        jLabel1.setText("Autor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 149, -1));
        add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 164, -1));

        cbTD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro", "Diccionario", "Mapas", "Tesis", "DVD", "VHS", "Cassettes", "CD", "Documento", "Periodicos", "Revistas" }));
        add(cbTD, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 110, 30));

        lbC3.setText("Campo 3");
        add(lbC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 149, -1));

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCodigo.setText("Código");
        add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 117, -1));

        lbE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbE.setText("Estado");
        add(lbE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 117, -1));

        lbC4.setText("Campo 3");
        add(lbC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 149, -1));
        add(txtEditorial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 164, -1));

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 90, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbTD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lbC1;
    private javax.swing.JLabel lbC2;
    private javax.swing.JLabel lbC3;
    private javax.swing.JLabel lbC4;
    private javax.swing.JLabel lbE;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JLabel txtCodigo;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtEditorial1;
    private javax.swing.JLabel txtEstado;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtNP;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUD;
    // End of variables declaration//GEN-END:variables
}
